[package]
name = "imgdiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
anyhow = "1.0.75"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
rustfft = "6.1.0"